include(${CMAKE_CURRENT_LIST_DIR}/system.cmake)

set(${CMAKE_PROJECT_NAME}_DEFINITIONS
    -DGLM_FORCE_RADIANS
    -DGLM_ENABLE_EXPERIMENTAL
)

if(${SYSTEM} STREQUAL "darwin")
set(${CMAKE_PROJECT_NAME}_DEFINITIONS
    -DVK_USE_PLATFORM_MACOS_MVK
)
elseif(${SYSTEM} STREQUAL "windows")
set(${CMAKE_PROJECT_NAME}_DEFINITIONS
    -DVK_USE_PLATFORM_WIN32_KHR
)
endif()